const INIT = 'CONTACTS/INIT';
const POST = 'CONTACTS/POST';
const LOAD_ALL = 'CONTACTS/LOAD_ALL';
const FETCH_ALL = 'CONTACTS/FETCH_ALL';
const APPLY_FILTER = 'CONTACTS/APPLY_FILTER';
const SET_SELECTED_ITEMS = 'CONTACTS/SET_SELECTED_ITEMS';

export default {
    INIT,
    POST,
    LOAD_ALL,
    FETCH_ALL,
    APPLY_FILTER,
    SET_SELECTED_ITEMS,
}